---
name: Generate translation report
on:
  pull_request:
    paths-ignore:
      - "translation_report.md"
jobs:
  report:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Generate report
        run: ./generate_report.py
      - name: Update report
        #run: ./commit_report.py ${{ secrets.GITHUB_TOKEN }}
        uses: test-room-7/action-update-file@v1.1.0
        with:
          file-path: translation_report.md
          commit-msg: Updated translation report
          github-token: ${{ secrets.GITHUB_TOKEN }}
